### ISSUE TITLE
Command - promo

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#16] opened 2019-01-09 17:30 UTC
Usage proposal:
1. Post `!promo` followed by content (hyperlink or attachment requirement) [#user# at least 1 hyperlink or attachment is required!]
2. Send  message to owner telling him that the promo is not yet active and must be reviewed
3. Promo is posted inside #promo-review (including message ID). Alfred adds two reactions: thumbsup/thumbsdown
4. Reviews need **1** interaction.
	- Reviewer **accept**: Post template as private message (include message id) [#user# An error as occurred! Please try again later or report to staff!]
	- Reviewer **decline**: 
		a. Post template as private message (!appeal info included)
                b. User uses !appeal command [#user# requested an appeal. @staff private support is needed! (Message ID: #idhere#)]
5. Remove reactions from message and add OK reaction

**Comment by TheRealDannyyy** [comment] 2019-01-10 17:57
Need new template, can't find old one.

**Comment by TheRealDannyyy** [comment] 2019-01-13 17:31
How is this going to work. What information is given?

**Comment by Armaldio** [comment] 2019-01-13 17:47
No templates needed
It a duplicate of the message

Le dim. 13 janv. 2019 à 12:31, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment] 2019-01-13 17:48
How is the removal going to work?

**Comment by Armaldio** [comment] 2019-01-13 17:54
As before, private message sent with ID of message

Le dim. 13 janv. 2019 à 12:48, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment] 2019-01-13 22:42
Added some minor details for the appeal process. The only problem I still see is possible unfair treatment based on emotions. (X doesn't like Y, therefor X will decline Y's content.)

**Comment by Armaldio** [comment] 2019-01-14 00:40
I can add some strict rules like:
- must contain 1 link or 1 attachment
- message must follow server rules
- message must not contain NSFW
- content must be one of the following:
Product release, major product update, makor general announcement (you can complete this list)

**Comment by TheRealDannyyy** [comment] 2019-01-25 17:00
I think we should completely move the process to PM's. It would look like this:

Usage proposal:
1. Post `!promo` in any channel, will be removed and Alfred will send a PM with promo template.
	- New template includes: rules, requirements and request to post content next.
2. User posts promotional content
3. If content is OK, Bot will ask to confirm or cancel the process
	- New template with confirm or cancel reactions
4. If confirmed, send message to owner telling him that the promo is not yet active and must be reviewed
5. Promo is posted inside #review (including message ID). Alfred adds two reactions: thumbsup/thumbsdown
4. Reviews need **1** interaction.
	- Reviewer **accept**: Post promotion inside #promotion channel
	- Reviewer **decline**: 
		a. Post template as private message (!appeal info included)
                b. User uses !appeal command [#user# requested an appeal. @staff private support is needed! (Message ID: #idhere#)]
5. Remove reactions from message and add OK reaction

**Comment by Armaldio** [comment] 2019-01-25 19:09
You made me change my mind: `I still have the feeling that this will not be used by most because it's too much work.`

Simplicity is more important. Maybe we'll just trust users.

1. Post !promo in any channel, will be removed and Alfred will send a PM with promo template.
	- New template includes: rules and requirements to post promotional content. Also include that if it doesn't fit the format, it will be removed without any warning. You can ask the staff afterward why it has been deleted.
2. Post is posted inside #promotion channel
3. If content is not OK, delete the message without warning

**Comment by TheRealDannyyy** [comment] 2019-01-25 19:55
Will do a template for that then.

**Comment by Armaldio** [comment] 2019-01-25 20:11
Do you fully agree on that?
No need to make unneeded templates

Le ven. 25 janv. 2019 à 14:55, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment] 2019-01-25 20:16
I would just do the template that includes all the required information you listed. It's not that much additional work for me and I don't mind existing work not being used.

**Comment by TheRealDannyyy** [comment] 2019-01-29 23:34
Final:
1. !promo #message#
2. post inside promotion
3. send success PM (promo-up template)

**Closed** 2019-02-02 23:45 UTC
Labels: enhancement
